name: ci-simulator
on:
  pull_request:
    branches:
      - develop

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - uses: action/setup-go@v4
        with:
          go-version: 1.18
      - run: go test -coverprofile=coverage.out
